[functions.ai-parse-workout]
verify_jwt = false

[functions.ai-parse-program]
verify_jwt = false

[functions.ai-clients-assistant]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.create-paymob-order]
verify_jwt = false

[functions.paymob-subscription]
verify_jwt = false

[functions.paymob-webhook]
verify_jwt = false